added monitorTX class & add to orchs list
noaOrMlnx/sonic-swss pull request #1
Opened 2019-12-04 15:13 UTC by noaOrMlnx

**What I did**: added class in orchagent named MonitorTXOrch and added it to the orchs list in orchdaemon class

**Why I did it**

**How I verified it**

**Details if related**

2019-12-04 18:14 UTC, stepanblyschak requested changes

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.h
> +        //MonitorTXOrch(DBConnector* ConfigDB, DBConnector* StateDB);
remove commented code

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.h
> +
extra empty line

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.h
> +
extra empty line

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.h
> +        // Table m_cfgTxErrTable;
remove commented code

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.h
> +
MonitorTXOrch inherits from virtual class, it is more correct to have virtual destructor for MonitorTXOrch

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.h
> +        bool isPortMapInitialized;
You use a lot of default intialized values for member fields, which is good.
Use the same for isPortMapInitialized and initialize by default to false

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.h
> +        // void insertStateToDB(sai_object_id_t portID, PortState state);
remove commented code

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.h
> +#endif
common practice is to insert newline at the end of file

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.h
> +        map<sai_object_id_t, uint64_t> m_TX_ERR_stat_by_port;
inconsistent naming, suggest to use m_txErrStatByPort

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.h
> +        map<sai_object_id_t, uint64_t> m_currTXCounters;
How this m_currTXCounters is different from m_TX_ERR_stat_by_port?

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +// constructor
basically useless comment

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +    // m_cfgTxErrTable(configDBTConnector.first, configDBTConnector.second)
remove commented code

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +    SWSS_LOG_NOTICE("creating monitor tx orch ...");
too verbose logging, it should be SWSS_LOG_DEBUG

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +    isPortMapInitialized = false;
Not required if you initialize in class definition

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +    SWSS_LOG_NOTICE("after init timer");
Not required log

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +    SWSS_LOG_NOTICE("all ports are ready");
General comment - NOTICE is too verbose for such log message, either delete or use SWSS_LOG_DEBUG

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +        if (p.m_type == Port::PHY) {
convert logic to more readable flow:

```c++
if (p.m_type != Port::PHY)
{
   continue;
}
// procceed.. 
```

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +void MonitorTXOrch::initTimer() {
General comment about sonic code style - ```{``` should be on new line

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +                // m_poolingPeriod = chrono::seconds(to_uint<uint32_t>(value));
remove commented code

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +                m_poolingPeriod = stoi(value);
value is user input.
Setting the value to some garbage will crash orchagent.
Here you need 
```c++
try
{
}
catch (...)
{
}
```

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +            }
Add ``` else ``` block with log message about unknown ```field``` value

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +            }
same else block is needed here

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +                SWSS_LOG_NOTICE("changing threshold to %s", value.c_str());
This kind of log messages are good to be with NOTICE level

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +        consumer.m_toSync.erase(it++);
This line of code worries me a bit.
An order is that first the current entry pointed by ```it``` will be erased and the the ```it``` will be incremented to the next one.
I believe this is undefined behavior when you operate on iterator which points to removed entry from map
A correct and simpler way is to:
```c++
it = consumer.m_toSync.erase(it)
```

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +// void MonitorTXOrch::doTask(Consumer &consumer) {
remove commented code

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +        m_portsState.emplace(currPortId, currState);
In state DB there should be no ID, it should be alias

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +    // TODO: check if need to flush here  - clear table before inserting new states.
your new state will override existing so no need to clear or flush

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +
extra newline

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +// void MonitorTXOrch::insertStateToDB(sai_object_id_t portID, PortState state) {
remove commented code

2019-12-04 18:14 UTC, stepanblyschak commented on orchagent/monitorTXorch.cpp
> +        m_stateTxErrTable.set(oidStr, fieldValuesVector);
there are two places where you set the state, can you have a small routine that sets the state so this part of code will be reused.

2019-12-05 07:23 UTC, noaOrMlnx commented on orchagent/monitorTXorch.h
> +        map<sai_object_id_t, uint64_t> m_currTXCounters;
m_txErrStatByPort is the data taken from counters - all tx errors until now. 
the current map contains the subtraction between the total count and the previous count. (so the check of threshold will be in the period defined).

2019-12-18 12:27 UTC, closed without merging